#!/usr/bin/env python
# coding: utf-8

# # Q1) Complex Numbers Subtraction

# In[7]:


import math

a1 = float(input("Enter the real number of first complex number: "))
b1 = float(input("Enter the imaginary number of first complex number: "))
a2 = float(input("Enter the real number of second complex number: "))
b2 = float(input("Enter the imaginary number of second complex number: "))

diff = complex(a1,b1) - complex(a2,b2)

print("\n\n")
print("The difference of the two given complex numbers is: ", diff)


# # Q2) Fourth root of the number

# In[12]:


import math

num = float(input("Enter the num: "))

root = math.sqrt(num)

f_root = math.sqrt(root)

print("The fourth root of the given number is: ", f_root)


# # Q3) Swap Numbers

# In[1]:


a = float(input("Enter a number: "))
b = float(input("Enter another number: "))

print("Values before swapping: a =",a,"b =",b)

temp = a
a = b
b = temp

print("Values after swapping: a =",a,"b =",b)


# # Q4) Swap Numbers without temporary variable

# In[19]:


a = float(input("Enter a number: "))
b = float(input("Enter another number: "))

print("Values before swapping: a =",a,"b =",b)

a,b = b,a


print("Values after swapping: a =",a,"b =",b)


# # Q5) Farenheit to Celsius and Kelvin conversion

# In[22]:


Farenheit = float(input("Enter the Farenheit value: "))

Celsius = 5/9*(Farenheit - 32)

Kelvin = 5/9*(Farenheit - 32) + 273

print("Celsius value = ",Celsius)
print("Kelvin vlaue = ",Kelvin)


# # Q6) Data types in Python

# In[2]:


a = 1
print(a, "= Data Type: ",type(a))

b = 1.1
print(b, "= Data Type: ",type(b))

c = 1 + 2j
print(c, "= Data Type: ",type(c))

d = True
print(d, "= Data Type: ",type(d))

e = 'Hello LetsUpgraders!'
print(e, "= Data Type: ",type(e))

f = []
print(f, "= Data Type: ",type(f))

g = ()
print(g, "= Data Type: ",type(g))

h = {}
print(h, "= Data Type: ",type(h))

i = {"a","b"}
print(i, "= Data Type: ",type(i))


# # Q7) Github profile setup

# 1) New Github account 
# 2) Create new repository
# 3) Name: LetsUpgrade AI-ML
# 4) Description: Assignments
# 5) Click Create button
# 6) Create a folder in the personal computer with name "Day 3" and save all the assignments in that folder.
# 7) Drag the folder into the repository
# 8) Commit changes
# 9) Copy the folder link from the Github and paste it in the assignment google form.

# In[ ]:




